import React, { useState } from 'react';

export const ClinicalCopier = ({ data, result }) => {
    const [copiedFormat, setCopiedFormat] = useState(null);

    const generateSOAP = () => {
        return `
MEDAURA AI - CLINICAL NOTE (SOAP)
---------------------------------
SUBJECTIVE:
Patient ${data.age}y ${data.gender} presenting with:
"${data.chiefComplaint}"
History: ${data.history || 'None recorded'}

OBJECTIVE:
Vitals:
- BP: ${data.vitals.bp || 'N/A'}
- HR: ${data.vitals.hr || 'N/A'}
- SpO2: ${data.vitals.spo2 || 'N/A'}%
- Temp: ${data.vitals.temp || 'N/A'}
- RR: ${data.vitals.rr || 'N/A'}

ASSESSMENT:
Primary AI Assessment: ${result.analysis?.conditions?.[0]?.name || 'Pending Analysis'}
Risk Level: ${result.triage?.level || 'Unknown'}
Confidence: ${result.analysis?.confidence || 0}%
Key Findings:
${result.analysis?.conditions?.map(c => `- ${c.name} (${c.probability}%)`).join('\n') || ''}

PLAN:
Suggested Triage: ${result.triage?.action || 'Standard Evaluation'}
Immediate Actions:
${result.checklist?.filter(c => c.checked).map(c => `- ${c.text}`).join('\n') || '- Conduct physical exam'}
---------------------------------
Generated by MedAura AI at ${new Date().toLocaleString()}
`.trim();
    };

    const generateSBAR = () => {
        return `
SBAR HANDOVER
-------------
SITUATION:
${data.age}y ${data.gender} with ${data.chiefComplaint}. 
Triage Category: ${result.triage?.level || 'Pending'}.

BACKGROUND:
History of ${data.history || 'nil significant'}.
Vitals: BP ${data.vitals.bp}, HR ${data.vitals.hr}, SpO2 ${data.vitals.spo2}%.

ASSESSMENT:
AI flags potential for ${result.analysis?.conditions?.[0]?.name || 'undifferentiated illness'}.
Red Flags: ${result.analysis?.redFlags?.join(', ') || 'None detailed'}.

RECOMMENDATION:
${result.triage?.action || 'Proceed with standard workup'}
-------------
`.trim();
    };

    const handleCopy = (format) => {
        let text = "";
        if (format === 'SOAP') text = generateSOAP();
        if (format === 'SBAR') text = generateSBAR();
        if (format === 'Simple') text = `Patient: ${data.age}${data.gender}\nComplaint: ${data.chiefComplaint}\nAssessment: ${result.triage?.level}`;

        navigator.clipboard.writeText(text);
        setCopiedFormat(format);
        setTimeout(() => setCopiedFormat(null), 2000);
    };

    return (
        <div className="flex gap-2 mt-2">
            <button
                onClick={() => handleCopy('SOAP')}
                className={`px-3 py-1.5 text-xs font-medium rounded-lg border transition-all ${copiedFormat === 'SOAP'
                        ? 'bg-green-500/20 border-green-500 text-green-400'
                        : 'bg-slate-800 border-slate-700 text-slate-300 hover:border-sky-500/50 hover:text-sky-400'
                    }`}
            >
                {copiedFormat === 'SOAP' ? '✓ Copied SOAP' : 'Copy SOAP'}
            </button>

            <button
                onClick={() => handleCopy('SBAR')}
                className={`px-3 py-1.5 text-xs font-medium rounded-lg border transition-all ${copiedFormat === 'SBAR'
                        ? 'bg-green-500/20 border-green-500 text-green-400'
                        : 'bg-slate-800 border-slate-700 text-slate-300 hover:border-sky-500/50 hover:text-sky-400'
                    }`}
            >
                {copiedFormat === 'SBAR' ? '✓ Copied SBAR' : 'Copy SBAR'}
            </button>
        </div>
    );
};
